### ISSUE TITLE
Release v1.3.2 fails with "No such file or directory"

### ISSUE THREAD

**Issue by cabrrtt** [h3rald/hastysite#2]
Executing hastysite v1.3.2 (Linux) fails with "No such file or directory"

**Comment by h3rald** [comment]
Mmm anything more specific? Which file/directory? Does it say?

Did you compile this yourself or did you use the pre-compiled binary?

**Comment by cabrrtt** [comment]
I just downloaded the pre-compiled binary, unpacked, chmod 755 and executed ./hastysite -h:
No such file or directory

I then downloaded the v1.3.0 pre-compiled binary which runs without issue

**Comment by h3rald** [comment]
This should be fixed by 05e0102acb1fbfe612f60c224b1890fc61f046e8.

**Comment by h3rald** [comment]
This should be addressed by release v1.3.3 -- tried on my linux server and it works. Please re-open if you still have the same problem.
