### ISSUE TITLE
Init fails to create scripts correctly

### ISSUE THREAD

**Issue by burningrooftop** [h3rald/hastysite#3]
After running hastysite init the scripts directory contains only 3 files: build.min, clean.min and page.min. Furthermore, clean.min contains the contents of post.min and the actual clean.min is missing.

The problem is in line 283 of hastysite.nim:

writeFile(dir/"scripts/clean.min", SCRIPT_POST)

**Comment by h3rald** [comment]
Well spotted, stupid mistake... fixing now, thanks!
