### ISSUE TITLE
[Error] installing hastysite and nifty 

### ISSUE THREAD

**Issue by nixfreak** [h3rald/hastysite#4]
nimble install hastysite                                                                             [11:08:59]
Downloading https://github.com/h3rald/hastysite using git
Downloading https://github.com/h3rald/nifty using git
  Verifying dependencies for nifty@1.2.2
       Tip: 4 messages have been suppressed, use --verbose to show them.
     Error: Unsatisfied dependency: nim (>= 1.4.0)
stack trace: (most recent call last)
/private/var/folders/81/zn5n71012mb48jwlptm46_m80000gq/T/nimblecache/nimscriptapi.nim(177, 29)
/private/var/folders/81/zn5n71012mb48jwlptm46_m80000gq/T/nimble_69521/githubcom_h3raldhastysite/hastysite_69521.nims(20, 8) installBefore
.choosenim/toolchains/nim-1.0.6/lib/system/nimscript.nim(252, 7) exec
.choosenim/toolchains/nim-1.0.6/lib/system/nimscript.nim(252, 7) Error: unhandled exception: FAILED: nimble install -y nifty [OSError]
       Tip: 5 messages have been suppressed, use --verbose to show them.
     Error: Exception raised during nimble script execution
aaronm:nim/ (stage*) $ nimble update                                                                                        [11:09:14]
Downloading Official package list
    Success Package list downloaded.
aaronm:nim/ (stage*) $ nimble install nifty                                                                                 [11:09:36]
Downloading https://github.com/h3rald/nifty using git
  Verifying dependencies for nifty@1.2.2
       Tip: 4 messages have been suppressed, use --verbose to show them.
     Error: Unsatisfied dependency: nim (>= 1.4.0)

`choosenim show                                                                         [11:16:30]
  Selected: 1.0.6
   Channel: stable
      Path: .choosenim/toolchains/nim-1.0.6

  Versions:  
            #devel
            1.4.8
            1.4.6
            1.4.4
            1.4.2
            1.4.0
            1.2.6
            1.2.4
            1.2.0
          * 1.0.6
            #version-1-6`

**Comment by h3rald** [comment]
Looks like you need Nim version 1.4.0 or higher. It's not going to run on 1.0.*...
