### ISSUE TITLE
[nix] Numerous missing/undocumented dependencies

### ISSUE THREAD

**Issue by trev-dev** [h3rald/hastysite#7]
This is a problem that seems to be a problem that rears its ugly head on NixOS a lot (for me?)

I thought it was worth mentioning regardless as building hastysite is not always as straightforward as one to two commands.

`nimble install hastysite` doesn't have as much compiler output, but it fails.

Using `nifty install` then `nim c -d:release` gets me this:

```
/nix/store/039g378vc3pc3dvi9dzdlrd0i4q93qwf-binutils-2.39/bin/ld: cannot find -lm: No such file or directory
/nix/store/039g378vc3pc3dvi9dzdlrd0i4q93qwf-binutils-2.39/bin/ld: cannot find -lm: No such file or directory
/nix/store/039g378vc3pc3dvi9dzdlrd0i4q93qwf-binutils-2.39/bin/ld: cannot find -lrt: No such file or directory
/nix/store/039g378vc3pc3dvi9dzdlrd0i4q93qwf-binutils-2.39/bin/ld: cannot find -lmarkdown: No such file or directory
/nix/store/039g378vc3pc3dvi9dzdlrd0i4q93qwf-binutils-2.39/bin/ld: cannot find -ldl: No such file or directory
/nix/store/039g378vc3pc3dvi9dzdlrd0i4q93qwf-binutils-2.39/bin/ld: cannot find -lc: No such file or directory
collect2: error: ld returned 1 exit status
Error: execution of an external program failed
```

I don't know why these things are implicitly elsewhere but not on my system

**Comment by h3rald** [comment]
Simplified installation (removed the need of using nifty).
